steps:
  - name: 'gcr.io/cloud-builders/git'
    args: ['lfs', 'pull']
  - name: node:10
    entrypoint: npm
    args: ['install']
  - name: node:10
    entrypoint: npm
    args: ['run', 'build']
  - name: node:10
    entrypoint: npm
    args: ['run', 'export']
  - name: gcr.io/cloud-builders/gsutil
    args: ["-m", "rsync", "-r", "-c", "-d", "./out", "gs://km-shared-files-423214"]
timeout: "600s"