steps:
  - name: 'gcr.io/kaiomeris/git-lfs'
    args: ['init']
  - name: 'gcr.io/kaiomeris/git-lfs'
    args: ['remote', 'add', 'origin', '[REPO_ADDRESS]']
  - name: 'gcr.io/kaiomeris/git-lfs'
    args: ['fetch']
  - name: 'gcr.io/kaiomeris/git-lfs'
    args: ['reset', '--soft', 'origin/$BRANCH_NAME']
  - name: 'gcr.io/kaiomeris/git-lfs'
    args: ['lfs', 'fetch']
  - name: node:10
    entrypoint: npm
    args: ['install']
  - name: node:10
    entrypoint: npm
    args: ['run', 'build']
  - name: node:10
    entrypoint: npm
    args: ['run', 'export']
  - name: gcr.io/cloud-builders/gsutil
    args: ["-m", "rsync", "-r", "-c", "-d", "./out", "gs://km-shared-files-423214"]
timeout: "600s"